const express=require("express")
const Approuter=express.Router()
const UserController=require("./AppControllers/UserController")
const WheyProteinController=require("./AppControllers/WheyProteinController")
const WheyProteinCartController=require("./AppControllers/WheyProteinCartController")
const UserProfileController=require("./AppControllers/UserProfileController")
const pythonController=require("./AppControllers/pythonController")
const ExerciseController=require("./AppControllers/ExcerciseController")
const WorkoutSaveController=require("./AppControllers/WorkoutSaveController")
const PaymentController=require("./AppControllers/PaymentCOntroller")
const Gemini=require("./AppControllers/gemini")
Approuter.post("/signin",UserController.UserLogin)
Approuter.post("/Adminsignin",UserController.AdminLogin)
Approuter.post("/signup",UserController.Newuser)
Approuter.post("/logout",UserController.LogoutUser)
Approuter.get("/wheydetails",WheyProteinController.GetWheyProteinDetails)
Approuter.post("/addWheycart",WheyProteinCartController.AddWheyProteinCartItems)
Approuter.post("/wheycartdetails",WheyProteinCartController.GetWheyProteinCartDetails)
Approuter.post("/UserProfileUpload",UserProfileController.StoreUserProfile)
Approuter.post("/SaveProfileImage",UserProfileController.SaveUserProfileImage)
Approuter.get("/userProfile/:userid",UserProfileController.GetUserProfileImage)
Approuter.post("/updateUser/:UserId",UserProfileController.UpdateUserdata)
Approuter.get("/pythonoutput",pythonController.GetPythonoutput)
Approuter.post("/filterWhey",WheyProteinController.GetFilteredWheyData)
Approuter.get("/exerciseData",ExerciseController.GetExerciseDetails)
Approuter.post("/saveWorkouts/:UserId",WorkoutSaveController.SaveWorkoutData)
Approuter.get("/getworkoutHistory/:UserId",WorkoutSaveController.GetWorkoutHistory)
Approuter.get("/getWheyProduct/:productId",WheyProteinController.GetWheyProductdetails)
Approuter.get("/getCartDetails/:UserId",WheyProteinCartController.GetFullCartDetails)
Approuter.post("/deleteCartItem",WheyProteinCartController.DeleteCartItems)
Approuter.post("/createOrderId",PaymentController.CreateOrderId)
Approuter.post("/verifyPayment",PaymentController.VerifyPayment)
Approuter.get("/getuserdetails",UserController.GetUserdetails)
Approuter.post("/updateStock",WheyProteinController.UpdateStocks)
Approuter.post("/getbaseImage",pythonController.GetBaseImage)
Approuter.post("/saveOrder/:UserId",UserController.SaveUserOrders)
Approuter.get("/getUserOrders",UserController.getUserOrders)
Approuter.post("/UserQuery",UserController.SendUserQueries)
Approuter.post("/gemini",Gemini.getgemini)
module.exports=Approuter
// https://backendfitness-50019322363.development.catalystappsail.in